### ISSUE TITLE
After Checkout, empty the Cart contents

### ISSUE THREAD

**Issue by vasouv** [vasouv/hardcoredistro#41]

**Comment by marekhavira** [comment]
Hallo, can i solve this issue? :) 
can you give me more informations?

**Comment by vasouv** [comment]
Of course you can!

The whole checkout process is badly written, I wanted to re-write it but didn't have time.

If you take a look at the jsf/CheckoutBean.java, the checkout process happens in the createCharge() method. So you'd probably have to empty the CartBean contents before it redirects to the success page but after the purchase is persisted.

Like I said, it's badly written but maybe you can enhance that part as well.

**Comment by marekhavira** [comment]
Sorry, but can you help me? 

When I try to log in to the application, it is still being thrown away. Login failed, even when config -> server config -> security -> Realm -> file added user ... user1, user2, user3

What am I doing wrong?

**Comment by vasouv** [comment]
Only thing I can think of is if you haven't added the users in the correct file realm group. That's how I have set it up.

![payara file realm](https://user-images.githubusercontent.com/65785/47237665-83170f00-d3e8-11e8-86b0-13084b9e47bd.png)

If that's the case, be my guest and update the README as well, now that I took a look at it it may be a little vague regarding the file realm users.
